### ISSUE TITLE
Support for local projections

### ISSUE THREAD

**Issue by dmcglone** [gerrymandr/python-mander#1]
The package uses Albers Equal Area [EPSG 2163](http://spatialreference.org/ref/epsg/2163/). Support defining local Albers Equal Area projections by state to calculate district scores.

**Comment by mxndrwgrdnr** [comment]
fix implemented [here](https://github.com/gerrymandr/python-mander/blob/master/mander/districts.py#L7-L8). User can now specify the `metricCrs`, when instantiating `District` object which denotes the desired projection for performing the calculations. The default value is set to `epsg:2163`
