### ISSUE TITLE
Refactor reock calculation to treat multipolygon districts individually

### ISSUE THREAD

**Issue by mxndrwgrdnr** [gerrymandr/python-mander#10]
The reock code currently merges all points of a multipolygon (i.e. a group of islands or a district that includes an island) and finds the area of the convex hull for all points at once. This greatly exaggerates the area of the circumscribing circle, which should instead be the summation of the areas of the convex hulls of the individual polygons included in the multipolygon.

**Comment by r-barnes** [comment]
The C++ branch does this.
