### ISSUE TITLE
Enable Continuous Integration

### ISSUE THREAD

**Issue by carlschroedl** [gerrymandr/python-mander#15]
Enable the project to be built on each pull request via a service like Travis CI so that contributors and maintainers are confident in the quality of the proposed code.

Martin Fowler has written [a good summary](https://martinfowler.com/articles/continuousIntegration.html) of the merits of continuous integration.

**Comment by r-barnes** [comment]
How do we move forward with this? Should I open an account on Travis?

**Comment by carlschroedl** [comment]
Yep! Pretty much! I talked with Justin Solomon. It sounds like he granted your GitHub user permissions to connect Travis to this repo. The next step would be to log in with your GitHub creds on https://travis-ci.org
Then authorize Travis to build this repo. Depending on what Justin has/has not done, you may also need to grant Travis some access to the Gerrymandr GitHub org too. Let me know if I can help!
