### ISSUE TITLE
Unexpected test results for Reock

### ISSUE THREAD

**Issue by dmcglone** [gerrymandr/python-mander#4]
Tests result scores running the Reock scores differ from the Reock scores calculated in Azavea's white paper. Potentially related to #3.

**Comment by aaronpdennis** [comment]
| test district | CD_CA_24 | CD_MA_9 |
|-------------|------------|----------|
| expected     | 0.3009       | 0.3407    |
| returned      | 0.1991        | 0.2714   |

**Comment by mxndrwgrdnr** [comment]
closing this out as it doesn't seem to be a bug but an unintended consequence of how we are treating multi-polygons. feature request opened in #10
