### ISSUE TITLE
Unexpected scores for convex hull on multi-polygon districts

### ISSUE THREAD

**Issue by aaronpdennis** [gerrymandr/python-mander#5]
The Convex Hull metric function is returning unexpected results for multi-polygon districts, such as those with islands.

| test district | CD_CA_24 | CD_MA_9 |
|-------------|------------|----------|
| expected     | 0.7427       | 0.4641    |
| returned      | 0.5173        | 0.3854   |

**Comment by mxndrwgrdnr** [comment]
closing this out as it doesn't seem to be a bug but an unintended consequence of how we are treating multi-polygons. feature request opened in #9
